export const project = {
  name: 'Vue GED',
  description: 'Un Google Photos-like auto-hébergé sur mon raspberry pi.',
  image: '/img/vue-photos.png',
  link: 'https://ged.cosmicnoise.dev/',
  order: 1,
  details: {
    front: {
      main: ['Vue.js', 'Typescript'],
      bundler: ['vite'],
      server: ['Nginx', 'Docker'],
      eslint: ['Airbnb'],
      packages: [
        'vue-router',
        'vue-i18n',
        'axios',
        'video.js',
        'vuelidate',
        'socket.io-client',
        'sass',
        'uppy',
      ],
    },
    back: {
      main: ['NestJS', 'Node.js 22', 'Typescript'],
      bundler: ['nest-cli'],
      server: ['Docker'],
      eslint: ['Airbnb'],
      packages: [
        'passport',
        'jsonwebtoken',
        'socket.io',
        'sequelize-typescript',
        'mysql2',
        'multer',
        'sharp',
        'yt-dlp-wrapper',
        'express',
        'fluent-ffmpeg',
        'bull',
        'puppeteer',
        'yup',
      ],
    },
    devops: [
      'Raspberry Pi 5',
      'Docker',
      'Nginx',
      'Let\'s Encrypt',
      'TUS Protocol',
      'Redis',
      'MySQL',
      'crontab',
    ],
  },
};
